["dust"]
    type = "archive-file"
    url = "https://github.com/bootandy/dust/releases/download/v1.2.4/dust-v1.2.4-x86_64-unknown-linux-musl.tar.gz"
    executable = true
    path = "dust-v1.2.4-x86_64-unknown-linux-musl/dust"
    checksum.sha256 = "4e313f9f854017e58a2ada4c0d1774677b8cf53d63ab55a991d5871d5f504452"
