{{- if .headless }}
["fish"]
    type = "archive-file"
    url = "https://github.com/fish-shell/fish-shell/releases/download/4.5.0/fish-4.5.0-linux-x86_64.tar.xz"
    executable = true
    path = "fish"
    checksum.sha256 = "a78d17517a6772a616d214a63f163ba8281c70834b71eeae9d1a37267e9e46d3"
{{- end }}

["dust"]
    type = "archive-file"
    url = "https://github.com/bootandy/dust/releases/download/v1.2.4/dust-v1.2.4-x86_64-unknown-linux-musl.tar.gz"
    executable = true
    path = "dust-v1.2.4-x86_64-unknown-linux-musl/dust"
    checksum.sha256 = "4e313f9f854017e58a2ada4c0d1774677b8cf53d63ab55a991d5871d5f504452"
